package ar.com.avaco.arc;


import java.util.ArrayList;
import java.util.List;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import ar.com.avaco.arc.utils.domain.Personaje;
import ar.com.avaco.arc.utils.domain.service.PersonajeService;

@RunWith(SpringJUnit4ClassRunner.class)
@DirtiesContext
@ContextConfiguration(locations={"classpath:arc/core/spring/applicationContext.xml"})
public class AutogeneratedMethodsTest {

	@Autowired
	private PersonajeService service;
	
	private Personaje entity;
	
	private List<Personaje> entityList;

	@Before
	public void setUp(){
		this.entity = new Personaje("Nombre3");
		
		this.entityList = new ArrayList<Personaje>();
		for (int i = 0; i < 5; i++) {
			this.entityList.add(new Personaje("Nombre" + i));
		}
	}
	
	@Test
	public void autogeneratedMethodsTest() {
		this.service.save(this.entity).getId();
		this.service.save(this.entityList);
		
		Assert.assertEquals(2, this.service.countByNombre("Nombre3"));
		Assert.assertEquals(2, this.service.getByNombre("Nombre3").size());
		Assert.assertEquals(2, this.service.getByNombreContaining("3").size());
	}
}